<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>name</key>
	<string>Configgy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\#.*$</string>
			<key>name</key>
			<string>comment.configgy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\u....</string>
					<key>name</key>
					<string>constant.character.escape.unicode</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\x..</string>
					<key>name</key>
					<string>constant.character.escape.hex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.simple</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_][-\w]*)(\.[a-zA-Z_][-\w]*)*</string>
			<key>name</key>
			<string>entity.configgy.keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?\d+(\.\d+)?</string>
			<key>name</key>
			<string>constant.number</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+$</string>
			<key>name</key>
			<string>invalid.trailing-whitespace</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.configgy</string>
	<key>uuid</key>
	<string>9A07AF9F-C341-4BE4-9E68-B768914621F9</string>
</dict>
</plist>
